<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\User::create([
            'id'    =>  1,
            'name' => 'Claudia Marcela Tuozzo',
            'username' => 'cmtuozzo',
            'tipo_rol'  => 1,
            'rol_usuario' => 1,
            'num_legajo' => 32,
            'fecha_ingreso' => '01/07/2006',
            'fecha_nacimiento' => '03/09/1963',
            'puesto' => 'Presidente',
            'email' => 'cmtuozzo@odontopraxis.com.ar',
            'contra_mail' => 'Newsist2018',
            'interno' => '114',
            'estado' => 'online',
            'ip_maquina' => '192.168.20.90',
            'password' => 'Odonto$Praxi$13A',
            'dir_onedrive' => '',
            'cuil'  =>  '23-16580570-4'
        ]);
    
        
            App\User::create([
                'id'    =>  2,
                'name' => 'Leonardo Andres Plehm',
                'username' => 'aplehm',
                'rol_usuario' => 3,
                'tipo_rol'  => 3,
                'num_legajo' => 137,
                'fecha_ingreso' => '03/04/2017',
                'fecha_nacimiento' => '30/07/1987',
                'puesto' => 'Departamento de Sistemas',
                'email' => 'sistemas@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/aplehm.png',
                'interno' => '181',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.40',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-33226836-9'
            ]);
            App\User::create([
                'id'    =>  3,
                'name' => 'Ivan Erland Picoy',
                'username' => 'ipicoy',
                'rol_usuario' => 3,
                'tipo_rol'  => 3,
                'num_legajo' => 127,
                'fecha_ingreso' => '04/01/2016',
                'fecha_nacimiento' => '28/07/1993',
                'puesto' => 'Departamento de Sistemas',
                'email' => 'sistemas@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/ipicoy.png',
                'interno' => '181',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.33',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-94007486-0'
            ]);
            App\User::create([
                'id'    =>  4,
                'name' => 'Patricia Palermo',
                'username' => 'ppalermo',
                'rol_usuario' => 3,
                'tipo_rol'  => 2,
                'num_legajo' => 97,
                'fecha_ingreso' => '01/09/2013',
                'fecha_nacimiento' => '11/01/1960',
                'puesto' => 'Departamento de Sistemas',
                'email' => 'pspalermo@odontopraxis.com.ar',
                'contra_mail' => 'PSPm1345',
                'foto' => 'storage/ppalermo.png',
                'interno' => '180',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.36',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-13765344-9'
            ]);
            App\User::create([
                'id'    =>  5,
                'name' => 'Agustin Gonzalo Polla',
                'username' => 'agpolla',
                'rol_usuario' => 3,
                'tipo_rol'  => 3,
                'num_legajo' => 146,
                'fecha_ingreso' => '14/02/2018',
                'fecha_nacimiento' => '05/09/1986',
                'puesto' => 'Departamento de Sistemas',
                'email' => 'agonzalo@odontopraxis.com.ar',
                'contra_mail' => 'NewAPG2018',
                'foto' => 'storage/agpolla.png',
                'interno' => '180',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.35',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-32532420-2'
            ]);
            App\User::create([
                'id'    =>  6,
                'name' => 'Marcelo Sifón',
                'username' => 'msifon',
                'rol_usuario' => 5,
                'tipo_rol'  => 2,
                'num_legajo' => 46,
                'fecha_ingreso' => '10/04/2008',
                'fecha_nacimiento' => '22/04/1975',
                'puesto' => 'Departamento de Recursos Humanos',
                'email' => 'admpersonal@odontopraxis.com.ar',
                'contra_mail' => 'RRHH2015',
                'foto' => 'storage/msifon.png',
                'interno' => '170',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.95',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  => '20-24650654-0'
            ]);
            App\User::create([
                'id'    =>  7,
                'name' => 'Laura Carimali',
                'username' => 'lcarimali',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 108,
                'fecha_ingreso' => '19/05/2014',
                'fecha_nacimiento' => '05/01/1990',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'newaudi7004',
                'foto' => 'storage/lcarimali.png',
                'interno' => '123',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.66',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-34977417-3'
            ]);
            App\User::create([
                'id'    =>  8,
                'name' => 'Brenda Lara Miller',
                'username' => 'blmiller',
                'rol_usuario' => 10,
                'tipo_rol'  => 3,
                'num_legajo' => 110,
                'fecha_ingreso' => '29/05/2014',
                'fecha_nacimiento' => '28/08/1990',
                'puesto' => 'Recepción',
                'email' => 'recepcion@odontopraxis.com.ar',
                'contra_mail' => 'ReCe1211bis',
                'foto' => 'storage/blmiller.png',
                'interno' => '100',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.72',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-35185211-4'
            ]);
            App\User::create([
                'id'    =>  9,
                'name' => 'Leandro Castro Vila',
                'username' => 'lcastrovila',
                'rol_usuario' => 12,
                'tipo_rol'  => 3,
                'num_legajo' => 50,
                'fecha_ingreso' => '03/04/2017',
                'fecha_nacimiento' => '30/07/1987',
                'puesto' => 'Departamento de Marketing',
                'email' => 'lcastrovila@odontopraxis.com.ar',
                'contra_mail' => 'RRHH2015',
                'interno' => '170',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.250',
                'password' => 'Lean1345$$',
                'dir_onedrive' => ''
            ]);
            App\User::create([
                'id'    =>  10,
                'name' => 'Alejandra Maria Cardoso',
                'username' => 'amcardoso',
                'rol_usuario' => 11,
                'tipo_rol'  => 3,
                'num_legajo' => 94,
                'fecha_ingreso' => '26/07/2013',
                'fecha_nacimiento' => '06/04/1975',
                'puesto' => 'Secretaria',
                'email' => 'secretaria@odontopraxis.com.ar',
                'contra_mail' => 'Secreta9832',
                'foto' => 'storage/acardozo.png',
                'interno' => '107',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.71',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-24563218-0'
            ]);
            App\User::create([
                'id'    =>  11,
                'name' => 'Julieta Rodriguez Lavalle',
                'username' => 'jrlavalle',
                'rol_usuario' => 6,
                'tipo_rol'  => 2,
                'num_legajo' => 103,
                'fecha_ingreso' => '02/05/2005',
                'fecha_nacimiento' => '20/07/1973',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'jrlavalle@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/jrlavalle.png',
                'interno' => '120',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.60',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-23505127-9'
            ]);
            App\User::create([
                'id'    =>  12,
                'name' => 'Monti Juan Carlos',
                'username' => 'jcmonti',
                'rol_usuario' => 9,
                'tipo_rol'  => 3,
                'num_legajo' => 26,
                'fecha_ingreso' => '11/07/2005',
                'fecha_nacimiento' => '05/07/1971',
                'puesto' => 'Administración',
                'email' => 'jcmonti@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/jcmonti.png',
                'interno' => '152',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.50',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-22285738-5'
            ]);
            App\User::create([
                'id'    =>  13,
                'name' => 'Elisa Ines Gonzalez',
                'username' => 'eigonzalez',
                'rol_usuario' => 9,
                'tipo_rol'  => 3,
                'num_legajo' => 57,
                'fecha_ingreso' => '14/12/2009',
                'fecha_nacimiento' => '10/01/1975',
                'puesto' => 'Administración',
                'email' => 'proveedores@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'interno' => '156',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.54',
                'password' => 'Odonto$Praxi$13A',
                'dir_onedrive' => '',
                'cuil'  =>  '27-23900592-1'
            ]);
            App\User::create([
                'id'    =>  14,
                'name' => 'Damian Miguel Saracena',
                'username' => 'dmsaracena',
                'rol_usuario' => 9,
                'tipo_rol'  => 3,
                'num_legajo' => 112,
                'fecha_ingreso' => '02/06/2014',
                'fecha_nacimiento' => '04/11/1986',
                'puesto' => 'Administración',
                'email' => 'dsaracena@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/dmsaracena.png',
                'interno' => '153',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.51',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '23-32640661-9'
            ]);
            App\User::create([
                'id'    =>  15,
                'name' => 'Andrés Daniel Dendarieta',
                'username' => 'addendarieta',
                'rol_usuario' => 9,
                'tipo_rol'  => 3,
                'num_legajo' => 132,
                'fecha_ingreso' => '02/01/2017',
                'fecha_nacimiento' => '24/05/1989',
                'puesto' => 'Administración',
                'email' => 'emision_factura@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/addendarieta.png',
                'interno' => '154',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.52',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-34051483-2'
            ]);
            App\User::create([
                'id'    =>  16,
                'name' => 'Silvina Ines Petric',
                'username' => 'sipetric',
                'rol_usuario' => 9,
                'tipo_rol'  => 3,
                'num_legajo' => 142,
                'fecha_ingreso' => '14/08/2017',
                'fecha_nacimiento' => '11/04/1968',
                'puesto' => 'Administración',
                'email' => 'emision_factura@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/sipetric.png',
                'interno' => '156',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.55',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '23-20204756-4'
            ]);
            App\User::create([
                'id'    =>  17,
                'name' => 'Jorge Dalmasso',
                'username' => 'jdalmasso',
                'rol_usuario' => 2,
                'tipo_rol'  =>  1,
                'num_legajo' => 12,
                'fecha_ingreso' => '14/10/2003',
                'fecha_nacimiento' => '06/05/1952',
                'puesto' => 'Gerencia',
                'email' => 'jdalmasso@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/jdalmasso.png',
                'interno' => '116',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.93',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-10232632-7'
            ]);
            App\User::create([
                'id'    =>  18,
                'name' => 'Gerardo Horacio Scialpi',
                'username' => 'ghscialpi',
                'rol_usuario' => 9,
                'tipo_rol'  =>  1,
                'num_legajo' => 140,
                'fecha_ingreso' => '03/07/2017',
                'fecha_nacimiento' => '07/11/1961',
                'puesto' => 'Administración',
                'email' => 'gscialpi@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/ghscialpi.png',
                'interno' => '150',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.93',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-14744377-4'
            ]);
            App\User::create([
                'id'    =>  19,
                'name' => 'Gabriela Arriola',
                'username' => 'garriola',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 15,
                'fecha_ingreso' => '22/03/2004',
                'fecha_nacimiento' => '21/02/1965',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/garriola.png',
                'interno' => '121',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.61',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-17148486-9'

            ]);
            App\User::create([
                'id'    =>  20,
                'name' => 'Alejandro Gamarra',
                'username' => 'agamarra',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 35,
                'fecha_ingreso' => '27/11/2006',
                'fecha_nacimiento' => '13/09/1965',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/agamarra.png',
                'interno' => '125',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.68',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-17445499-0'
            ]);
            App\User::create([
                'id'    =>  21,
                'name' => 'Mariana Alicia Zorzano',
                'username' => 'mazorzano',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 76,
                'fecha_ingreso' => '16/04/2012',
                'fecha_nacimiento' => '12/07/1964',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/mazorzano.png',
                'interno' => '124',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.69',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-17172369-3'
            ]);
            App\User::create([
                'id'    =>  22,
                'name' => 'Julia Marina Di Pietro',
                'username' => 'jmdipietro',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 105,
                'fecha_ingreso' => '20/01/2014',
                'fecha_nacimiento' => '25/03/1979',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/jmdipietro.png',
                'interno' => '127',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.64',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-27187307-2'
            ]);
            App\User::create([
                'id'    =>  23,
                'name' => 'Agustina Carla Gonzalez',
                'username' => 'acgonzalez',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 114,
                'fecha_ingreso' => '04/05/2015',
                'fecha_nacimiento' => '25/08/1992',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/acgonzalez.png',
                'interno' => '126',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.65',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-40633334-0'
            ]);
            App\User::create([
                'id'    =>  24,
                'name' => 'Melanie Agustina Zambelli',
                'username' => 'mazambelli',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 115,
                'fecha_ingreso' => '01/06/2015',
                'fecha_nacimiento' => '31/07/1989',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'autorizaciones@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/mazambelli.png',
                'interno' => '122',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.67',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-34683963-0'
            ]);
            App\User::create([
                'id'    =>  25,
                'name' => 'Guillermo Emiliano Pastó',
                'username' => 'gepasto',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 118,
                'fecha_ingreso' => '06/07/2015',
                'fecha_nacimiento' => '13/10/1989',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'autorizaciones@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/gepasto.png',
                'interno' => '129',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.62',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-34999219-2'
            ]);
            App\User::create([
                'id'    =>  26,
                'name' => 'Luisina Garzia',
                'username' => 'lgarzia',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 119,
                'fecha_ingreso' => '03/08/2015',
                'fecha_nacimiento' => '15/04/1982',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'autorizaciones@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/lgarzia.png',
                'interno' => '130',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.70',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-28779873-9'
            ]);
            App\User::create([
                'id'    =>  27,
                'name' => 'Alberto Carlos Dominguez',
                'username' => 'acdominguez',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 145,
                'fecha_ingreso' => '08/11/2017',
                'fecha_nacimiento' => '25/10/1987',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'autorizaciones@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/acdominguez.png',
                'interno' => '128',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.63',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '20-33373559-9'
            ]);

            App\User::create([
                'id'    =>  28,
                'name' => 'Yanina Marisel Vergara',
                'username' => 'ymvergara',
                'rol_usuario' => 7,
                'tipo_rol'  => 3,
                'num_legajo' => 86,
                'fecha_ingreso' => '25/02/2013',
                'fecha_nacimiento' => '14/04/1985',
                'puesto' => 'Departamento de Profesionales',
                'email' => 'autorizaciones@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/ymvergara.png',
                'interno' => '141',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.83',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-31534535-4'
            ]);

            App\User::create([
                'id'    =>  29,
                'name' => 'Mariela Vanesa Sirvent',
                'username' => 'mvsirvent',
                'rol_usuario' => 7,
                'tipo_rol'  => 3,
                'num_legajo' => 141,
                'fecha_ingreso' => '03/04/2017',
                'fecha_nacimiento' => '13/10/1987',
                'puesto' => 'Departamento de Profesionales',
                'email' => 'profesionales@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/mvsirvent.png',
                'interno' => '142',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.82',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-27355266-4'
            ]);

            App\User::create([
                'id'    =>  30,
                'name' => 'Marta Ojeda',
                'username' => 'mojeda',
                'rol_usuario' => 7,
                'tipo_rol'  => 2,
                'num_legajo' => 87,
                'fecha_ingreso' => '01/03/2013',
                'fecha_nacimiento' => '19/06/1957',
                'puesto' => 'Departamento de Profesionales',
                'email' => 'mojeda@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/mojeda.png',
                'interno' => '140',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.81',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-13125656-1'
            ]);

            App\User::create([
                'id'    =>  31,
                'name' => 'Lidia Draghi',
                'username' => 'ldraghi',
                'rol_usuario' => 9,
                'tipo_rol'  => 1,
                'num_legajo' => 1,
                'fecha_ingreso' => '20/12/2001',
                'fecha_nacimiento' => '30/06/1960',
                'puesto' => 'Administración',
                'email' => 'ldraghi@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'foto' => 'storage/ldraghi.png',
                'interno' => '151',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.92',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-13965029-3'
            ]);
            App\User::create([
                'id'    =>  32,
                'name' => 'Diego Jesus Zaragoza',
                'username' => 'djzaragoza',
                'rol_usuario' => 3,
                'tipo_rol'  => 3,
                'num_legajo' => 147,
                'fecha_ingreso' => '14/02/2018',
                'fecha_nacimiento' => '11/03/1982',
                'puesto' => 'Departamento de Sistemas',
                'email' => 'dzaragoza@odontopraxis.com.ar',
                'contra_mail' => 'NewAPG2018',
                'foto' => 'storage/djzaragoza.png',
                'interno' => '180',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.34',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '23-29093388-9'
            ]);
            App\User::create([
                'id'    =>  33,
                'name' => 'Usuario Demo',
                'username' => 'udemo',
                'rol_usuario' => 8,
                'tipo_rol'  => 3,
                'num_legajo' => 500,
                'fecha_ingreso' => '03/04/2017',
                'fecha_nacimiento' => '30/07/1987',
                'puesto' => 'Departamento de Desarrollo',
                'email' => 'demo@odontopraxis.com.ar',
                'contra_mail' => 'demo',
                'interno' => '180',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.35',
                'password' => 'Demo$$1345',
                'dir_onedrive' => '',
            ]);

            App\User::create([
                'id'    =>  34,
                'name' => 'Mariana Elizabeth Erdmann',
                'username' => 'meerdmann',
                'rol_usuario' => 5,
                'foto' => 'storage/meerdmann.png',
                'tipo_rol'  => 3,
                'num_legajo' => 72,
                'fecha_ingreso' => '20/07/2009',
                'fecha_nacimiento' => '10/03/1985',
                'puesto' => 'Call-center',
                'email' => 'turnos@central-integral.com.ar',
                'contra_mail' => 'demo',
                'interno' => '200',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.41',
                'password' => 'Odonto$Praxi$13A',
                'dir_onedrive' => '',
                'cuil'  =>  '27-31533059-4'
            ]);
            App\User::create([
                'id'    =>  35,
                'name' => 'Julieta Garcia',
                'username' => 'jgarcia',
                'foto' => 'storage/jgarcia.png',
                'rol_usuario' => 5,
                'tipo_rol'  => 3,
                'num_legajo' => 74,
                'fecha_ingreso' => '02/11/2009',
                'fecha_nacimiento' => '22/06/1987',
                'puesto' => 'Call-center',
                'email' => 'turnos@central-integral.com.ar',
                'contra_mail' => 'demo',
                'interno' => '200',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.42',
                'password' => 'Odonto$Praxi$13A',
                'dir_onedrive' => '',
                'cuil'  =>  '27-33112107-5'
            ]);

            App\User::create([
                'id'    =>  36,
                'name' => 'Micaela Hermida',
                'username' => 'mhermida',
                'rol_usuario' => 5,
                'tipo_rol'  => 3,
                'num_legajo' => 78,
                'fecha_ingreso' => '23/04/2012',
                'fecha_nacimiento' => '26/02/1987',
                'puesto' => 'Call-center',
                'email' => 'turnos@central-integral.com.ar',
                'contra_mail' => 'demo',
                'interno' => '200',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.43',
                'password' => 'Odonto$Praxi$13A',
                'dir_onedrive' => '',
                'cuil'  =>  '27-32905200-7'
            ]);

            App\User::create([
                'id'    =>  37,
                'name' => 'Vanesa Carolina Villareal',
                'username' => 'vcvillareal',
                'rol_usuario' => 5,
                'tipo_rol'  => 3,
                'num_legajo' => 150,
                'fecha_ingreso' => '12/06/2018',
                'fecha_nacimiento' => '19/05/1991',
                'puesto' => 'Call-center',
                'email' => 'turnos@central-integral.com.ar',
                'contra_mail' => 'demo',
                'interno' => '200',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.44',
                'password' => 'Odonto$Praxi$13A',
                'dir_onedrive' => '',
                'cuil'  =>  '27-35976985-2'
            ]);

            App\User::create([
                'id'    =>  38,
                'name' => 'Eugenia Sarranz Ibañez ',
                'username' => 'eisarranz',
                'rol_usuario' => 5,
                'tipo_rol'  => 3,
                'num_legajo' => 151,
                'fecha_ingreso' => '13/06/2018',
                'fecha_nacimiento' => '28/04/1998',
                'puesto' => 'Call-center',
                'email' => 'turnos@central-integral.com.ar',
                'contra_mail' => 'demo',
                'interno' => '200',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.45',
                'password' => 'Odonto$Praxi$13A',
                'dir_onedrive' => '',
                'cuil'  =>  '27-41105620-7'
            ]);
        
            App\User::create([
                'id'    =>  39,
                'name' => 'Leguizamon Andrea Patricia',
                'username' => 'apleguizamon',
                'rol_usuario' => 6,
                'tipo_rol'  => 3,
                'num_legajo' => 152,
                'fecha_ingreso' => '24/09/2018',
                'fecha_nacimiento' => '22/04/1986',
                'puesto' => 'Departamento de Auditoría',
                'email' => 'auditoria@odontopraxis.com.ar',
                'contra_mail' => 'Newsist2018',
                'interno' => '123',
                'estado' => 'online',
                'ip_maquina' => '192.168.20.66',
                'dir_onedrive' => '',
                'password' => 'Odonto$Praxi$13A',
                'cuil'  =>  '27-32403820-0'

            ]);
             
    }
}
